config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/auth/twitter', as: :login

  get '/auth/twitter/callback', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy', as: :logout

  resources :tweets
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
    user = User.find_by(uid: auth_info.uid)
    user.screen_name              = auth_info.extra.raw_info.screen_name
    user.image                    = auth_info.info.image
    user.description              = auth_info.info.description
    user.followers_count          = auth_info.extra.raw_info.followers_count
    user.friends_count            = auth_info.extra.raw_info.friends_count
    user.save
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def api_data(current_user)
    TwitterService.new(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new
  end

  def create
    @tweet_message = api_data(current_user).client.update(params[:tweet][:message])
    redirect_to root_path
  end

  def update
    twitter_data = api_data(current_user)
    twitter_data.client.favorite(params[:id].to_i)
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      @twitter_data = api_data(current_user)
      @user = current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweet4trump</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<nav>
 <div class="nav-wrapper color blue">
   <a href="#" class="brand-logo center"></a>
   <a href="#" class="brand-logo">Tweet4Trump</a>
   <ul id="nav-mobile" class="right hide-on-med-and-down">
     <% if current_user %>
     <%= link_to "Logout", logout_path %>
     <% end %>
   </ul>
 </div>
</nav>

<div class="container">

  <% if current_user %>

    <div class="container">
        <div class="card-panel grey lighten-5 z-depth-1">
          <div class="row valign-wrapper">
            <div class="col s2">
              <img src="<%= @user.image %>" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
            </div>
            <div class="col s8">
              <span class="black-text">
                <%= @user.name %><br>
                My followers count:<%= @user.followers_count %><br>
                My friends count: <%= @user.friends_count %><br>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="row">

      <div class="container">
        <%= form_for :tweet, url: tweets_path, method: :post do |f| %>
          <%= f.text_field :message %>
          <%= f.submit "Tweet", class: 'blue' %>
        <% end %>
      </div>
    </div>

<div class="container">

<div class="card-content black-text center">
  <span class="card-title">My Tweets</span>
  <ul><% @twitter_data.client.home_timeline.take(5).each do |tweet| %>
    <li>
      <div class="card black-text">
        <% if tweet.media.present? %>
          <img src="<%= tweet.media.first.media_url %>" >
        <% end %><br>
      <%= tweet.text %>
      <%= link_to "Favorite", tweet_path(tweet.id), method: :put, class: 'blue-text' %>
      <%= tweet.favorite_count %>
    </div>
  </li>
  <% end %>
</ul>
</div>

<% else %>

<div class="container">
<div class="center">
 <%= button_to "Login", login_path, class: 'blue' %>
 </div>
 </div>

<% end %>
</div>